version: '3.8'
services:
  cache:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6380:6379'
    volumes:
      - welouxor_cache_data:/bitnami/redis/data
      
  data:
    image:  bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_DATABASE=welouxor
      - POSTGRESQL_USERNAME=welouxor_root
      - POSTGRESQL_PASSWORD=zy4fVNVu

    ports:
      - '5433:5432'
    volumes:
     - 'welouxor_db_data:/bitnami/postgresql'
    
volumes:
  welouxor_cache_data:
    driver: local
  welouxor_db_data:
    driver: local